import { Device, TestSession, UploadedApp } from './types';

export const dummyDevices: Device[] = [
  {
    id: '1',
    name: 'iPhone 14 Pro',
    os: 'iOS',
    osVersion: '17.2',
    status: 'available',
    specs: {
      ram: '6GB',
      storage: '256GB',
      processor: 'A16 Bionic',
    },
    location: 'US East',
  },
  {
    id: '2',
    name: 'Samsung Galaxy S23',
    os: 'Android',
    osVersion: '14',
    status: 'busy',
    specs: {
      ram: '8GB',
      storage: '256GB',
      processor: 'Snapdragon 8 Gen 2',
    },
    location: 'US West',
  },
  {
    id: '3',
    name: 'Google Pixel 7',
    os: 'Android',
    osVersion: '14',
    status: 'available',
    specs: {
      ram: '8GB',
      storage: '128GB',
      processor: 'Google Tensor G2',
    },
    location: 'Europe',
  },
  {
    id: '4',
    name: 'iPad Pro 12.9"',
    os: 'iOS',
    osVersion: '17.1',
    status: 'available',
    specs: {
      ram: '8GB',
      storage: '512GB',
      processor: 'M2',
    },
    location: 'US East',
  },
  {
    id: '5',
    name: 'iPhone 13',
    os: 'iOS',
    osVersion: '17.0',
    status: 'offline',
    specs: {
      ram: '4GB',
      storage: '128GB',
      processor: 'A15 Bionic',
    },
    location: 'Asia',
  },
  {
    id: '6',
    name: 'OnePlus 11',
    os: 'Android',
    osVersion: '14',
    status: 'available',
    specs: {
      ram: '16GB',
      storage: '256GB',
      processor: 'Snapdragon 8 Gen 2',
    },
    location: 'US West',
  },
  {
    id: '7',
    name: 'iPhone 15 Pro Max',
    os: 'iOS',
    osVersion: '17.3',
    status: 'busy',
    specs: {
      ram: '8GB',
      storage: '512GB',
      processor: 'A17 Pro',
    },
    location: 'US East',
  },
  {
    id: '8',
    name: 'Samsung Galaxy S24 Ultra',
    os: 'Android',
    osVersion: '14',
    status: 'available',
    specs: {
      ram: '12GB',
      storage: '512GB',
      processor: 'Snapdragon 8 Gen 3',
    },
    location: 'Europe',
  },
];

export const dummySessions: TestSession[] = [
  {
    id: 'ses-1',
    deviceId: '1',
    deviceName: 'iPhone 14 Pro',
    appName: 'MyApp v2.1.0',
    duration: '15m 23s',
    startTime: '2024-03-15T10:30:00',
    endTime: '2024-03-15T10:45:23',
    status: 'completed',
    logs: ['Session started', 'App launched successfully', 'Test completed'],
  },
  {
    id: 'ses-2',
    deviceId: '2',
    deviceName: 'Samsung Galaxy S23',
    appName: 'TestApp v1.0.5',
    duration: '8m 45s',
    startTime: '2024-03-15T09:15:00',
    endTime: '2024-03-15T09:23:45',
    status: 'completed',
  },
  {
    id: 'ses-3',
    deviceId: '3',
    deviceName: 'Google Pixel 7',
    appName: 'MyApp v2.1.0',
    duration: '22m 10s',
    startTime: '2024-03-14T16:20:00',
    endTime: '2024-03-14T16:42:10',
    status: 'completed',
  },
  {
    id: 'ses-4',
    deviceId: '7',
    deviceName: 'iPhone 15 Pro Max',
    appName: 'BetaApp v3.0.0',
    duration: '5m 12s',
    startTime: '2024-03-15T11:00:00',
    status: 'running',
  },
  {
    id: 'ses-5',
    deviceId: '4',
    deviceName: 'iPad Pro 12.9"',
    appName: 'UITestApp v1.2.3',
    duration: '12m 30s',
    startTime: '2024-03-14T14:10:00',
    endTime: '2024-03-14T14:22:30',
    status: 'failed',
  },
];

export const dummyApps: UploadedApp[] = [
  {
    id: 'app-1',
    name: 'MyApp.apk',
    version: '2.1.0',
    platform: 'Android',
    size: '45.2 MB',
    uploadedAt: '2024-03-15T08:30:00',
    status: 'ready',
  },
  {
    id: 'app-2',
    name: 'MyApp.ipa',
    version: '2.1.0',
    platform: 'iOS',
    size: '52.8 MB',
    uploadedAt: '2024-03-15T08:32:00',
    status: 'ready',
  },
  {
    id: 'app-3',
    name: 'TestApp.apk',
    version: '1.0.5',
    platform: 'Android',
    size: '38.4 MB',
    uploadedAt: '2024-03-14T15:20:00',
    status: 'ready',
  },
  {
    id: 'app-4',
    name: 'BetaApp.ipa',
    version: '3.0.0',
    platform: 'iOS',
    size: '67.1 MB',
    uploadedAt: '2024-03-14T12:10:00',
    status: 'processing',
  },
];
